version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env # Passes API_KEY_GENAI to the container
    environment:
      - FRONTEND_URL=http://localhost:8080
      - GEMINI_MODEL=gemini-2.5-flash # Example: Override the default model
    volumes:
      - ./backend:/app/backend # Mounts the local backend code for live reloading

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
